# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


# development:
#   <<: *default
#   database: amg_service_development
# test:
#   <<: *default
#   database: amg_service_test

# production:
#   primary: &primary_production
#     <<: *default
#     database: amg_service_production
#     username: amg_service
#     password: <%= ENV["AMG_SERVICE_DATABASE_PASSWORD"] %>
#   cache:
#     <<: *primary_production
#     database: amg_service_production_cache
#     migrations_paths: db/cache_migrate
#   queue:
#     <<: *primary_production
#     database: amg_service_production_queue
#     migrations_paths: db/queue_migrate
#   cable:
#     <<: *primary_production
#     database: amg_service_production_cable
#     migrations_paths: db/cable_migrate

default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3

